replicaCount: 1

image:
  repository: stepin-template
  pullPolicy: IfNotPresent 
  tag: "v0.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  port: 8080

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: lite.bcys.com
      paths:
        - path: /stepin
          pathType: Prefix
  tls: []
